INSERT INTO article (article_id, title, summary) values(1, 'Nasa 2020 robot rover to target Jezero ''lake'' crater', 'America''s next robot rover will be sent to a 50km-wide depression that once had water running through it.');
INSERT INTO article (article_id, title, summary) values(2, 'The physicist called Einstein - but not the one you think', 'There is debate around how much Albert Einstein''s first wife, Mileva, contributed to his discoveries.');
INSERT INTO article (article_id, title, summary) values(3, 'Elon Musk renames his BFR spacecraft Starship', 'The entrepreneur would not reveal why he had renamed the craft, which has still not yet been built.');
INSERT INTO article (article_id, title, summary) values(4,'E. coli outbreak: Romaine lettuce probed in US and Canada', 'At least 50 people in the US and Canada have been infected, health officials say.');
INSERT INTO article (article_id, title, summary) values(5, 'Dead sperm whale found in Indonesia had ingested ''6kg of plastic''', 'The dead sperm whale, which washed ashore in Indonesia, had ingested nearly 6kg of plastic waste.');
INSERT INTO article (article_id, title, summary) values(6, 'Climate change: Report raises new optimism over industry', 'Cutting emissions from heavy industry would generate savings and boost economic growth, commission argues.');
INSERT INTO article (article_id, title, summary) values(7, 'UK industry to make new ''Hotbirds''', 'British industry will build new spacecraft for telecoms operator Eutelsat''s flagship TV distribution network.');
INSERT INTO article (article_id, title, summary) values(8, 'Wombat poop: Scientists reveal mystery behind cube-shaped droppings', 'Scientists discover how the marsupials are the only known species producing cube-shaped faeces.');
INSERT INTO article (article_id, title, summary) values(9, 'Ash dieback: Seed orchards could help species recover sooner', 'A scientist at the John Innes Centre in Norwich says resistant seeds could help beat the fatal disease.');
INSERT INTO article (article_id, title, summary) values(10,'Kilogram gets a new definition', 'Scientists take the massive decision to change the definition of the kilogram.');
INSERT INTO article (article_id, title, summary) values(11,'Greenland ice sheet hides huge ''impact crater''', 'Scientists find evidence that an iron asteroid slammed into the Earth deep inside the Arctic Circle.');
INSERT INTO article (article_id, title, summary) values(12,'Climate change: Worries over CO2 emissions from intensifying wildfires', 'Rising numbers of extreme wildfires could result in a significant increase in CO₂ emissions, scientists have warned.');
INSERT INTO article (article_id, title, summary) values(13,'Exoplanet discovered around neighbouring star', 'Astronomers have discovered a planet around one of the closest stars to our Sun.');
INSERT INTO article (article_id, title, summary) values(14,'Climate change: Report says ''cut lamb and beef''', 'The number of sheep and cattle in the UK should be reduced to help combat climate change, a report says.');
INSERT INTO article (article_id, title, summary) values(15,'''Conservation successes'' bring hope for mountain gorilla', 'Mountain gorilla: Conservation efforts appear to be paying off for large, charismatic animals.');

INSERT INTO user (user_id, firstname, surname) values(1, 'Ada', 'Lovelace');
INSERT INTO user (user_id, firstname, surname) values(2, 'Grace', 'Hopper');
INSERT INTO user (user_id, firstname, surname) values(3, 'Hedy', 'Lamarr');
INSERT INTO user (user_id, firstname, surname) values(4, 'Jean', 'Bartik');
INSERT INTO user (user_id, firstname, surname) values(5, 'Marissa', 'Mayer');
INSERT INTO user (user_id, firstname, surname) values(6, 'Francis', 'Allen');
INSERT INTO user (user_id, firstname, surname) values(7, 'Barbara', 'Liskov');
INSERT INTO user (user_id, firstname, surname) values(8, 'Shafi', 'Goldwasser');
INSERT INTO user (user_id, firstname, surname) values(9, 'Karen', 'Spark Jones');
INSERT INTO user (user_id, firstname, surname) values(10, 'Mirella', 'Lapata');
INSERT INTO user (user_id, firstname, surname) values(11, 'Diane', 'Kelly');
INSERT INTO user (user_id, firstname, surname) values(12, 'Emine', 'Yilmaz');
INSERT INTO user (user_id, firstname, surname) values(13, 'Jaime', 'Teevan');